### ISSUE TITLE
Serialization errors on Custom Managed Records with complex types

### ISSUE THREAD

**Issue by darianmiller** [paolo-rossi/delphi-neon#44] opened 2022-04-04 02:28 UTC
Add a new field to your TPerson class in Demo.Neon.Entities for this TExampleCMR to replicate "invalid pointer operation" exception on serialization
````
  TExampleCMR = Record
  Public
    Info:string;
    KeyPairs: TDictionary<string, string>;

    class operator Initialize(out Dest:TExampleCMR);
    class operator Finalize(var Dest:TExampleCMR);
  End;
...

class operator TExampleCMR.Initialize(out Dest:TExampleCMR);
begin
  Dest.KeyPairs := TDictionary<string, string>.Create;
end;
class operator TExampleCMR.Finalize(var Dest:TExampleCMR);
begin
  Dest.KeyPairs.Free;
end;
````

**Comment by paolo-rossi** [comment] 2022-04-17 09:10
Hi Darian,

sorry it took me a long time to look at the issue...

can you tell me what Delphi version were you using? 

I tried with Delphi 11.1 and the serialization process seems to be ok... I have some problems in deserialization though (sure I have to look into this issue a little bit more)

Ciao,
Paolo.

**Comment by darianmiller** [comment] 2022-04-17 20:11
I am using 11.1 and pulled your latest code from GitHub.

**Comment by paolo-rossi** [comment] 2022-07-06 08:11
Darian,

finally I had some time to look at this issue again and I found something strange going on with CMRs containing references associated with a copy operation (explicit/implicit assign, parameter passing etc...) but the issue is not in Neon is in the RTL!

Problem is that Neon to do the (de)serialization routines does some copy of the value-based T, hence the problem surface even if you don't explicitly copy the record.

Attached you will find a small Delphi (RTL only) project that highlights this problem.. 
I have to admit that I haven't played enough with CMR so it's possible that I am missing something obvious here.

I'll investigate this further but I think I will close this issue 'cause I this it's more of a Delphi-related (bug?) issue.

Thanks for your time,
Paolo.

P.S.: Darian, I am in Delphi Developers group in Telegram or Discord, if you want to continue this discussion, send me a message there (or by email)

**Closed** 2022-07-06 16:37 UTC
